name: release-please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release
        with:
          package-name: node-gyp
          release-type: node
          changelog-types: >
              [{"type":"feat","section":"Features","hidden":false},
                {"type":"fix","section":"Bug Fixes","hidden":false},
                {"type":"gyp","section":"Core","hidden":false},
                {"type":"lib","section":"Core","hidden":false},
                {"type":"deps","section":"Core","hidden":false},
                {"type":"doc","section":"Doc","hidden":false}]
